INF_APP_ID = 'xxxxxxxx'
INF_APP_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
CLIENT_ACCESS_TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
FIREBASE_API_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
FIREBASE_AUTH_DOMAIN = ''
FIREBASE_DB_URL = 'https://your-firebase-url.firebaseio.com/'
FIREBASE_STORAGE_BUCKET = ''
